#import "EntityID.h"
#import "EventID.h"
#import "Vector3Float.h"
#import "SystemID.h"
#import "IffFundamentalData.h"
#import <Foundation/Foundation.h>
#import "DistributedEmissionsFamilyPdu.h"
#import "DataInput.h"
#import "DataOutput.h"


// 5.3.7.4.1: Navigational and IFF PDU. COMPLETE

// Copyright (c) 2007-2009, MOVES Institute, Naval Postgraduate School. All rights reserved. 
//
// @author DMcG

@interface IffAtcNavAidsLayer1Pdu : DistributedEmissionsFamilyPdu
{
  /** ID of the entity that is the source of the emissions */
  EntityID *emittingEntityId; 

  /** Number generated by the issuing simulation to associate realted events. */
  EventID *eventID; 

  /** Location wrt entity. There is some ambugiuity in the standard here, but this is the order it is listed in the table. */
  Vector3Float *location; 

  /** System ID information */
  SystemID *systemID; 

  /** padding */
  unsigned short pad2; 

  /** fundamental parameters */
  IffFundamentalData *fundamentalParameters; 

}

@property(readwrite, retain) EntityID* emittingEntityId; 
@property(readwrite, retain) EventID* eventID; 
@property(readwrite, retain) Vector3Float* location; 
@property(readwrite, retain) SystemID* systemID; 
@property(readwrite, assign) unsigned short pad2; 
@property(readwrite, retain) IffFundamentalData* fundamentalParameters; 

-(id)init; // Initializer
-(void)dealloc;
-(void)marshalUsingStream:(DataOutput*) dataStream;
-(void)unmarshalUsingStream:(DataInput*) dataStream;

-(int)getMarshalledSize;

@end

// Copyright (c) 1995-2009 held by the author(s).  All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
//  are met:
// 
//  * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
// * Neither the names of the Naval Postgraduate School (NPS)
//  Modeling Virtual Environments and Simulation (MOVES) Institute
// (http://www.nps.edu and http://www.MovesInstitute.org)
// nor the names of its contributors may be used to endorse or
//  promote products derived from this software without specific
// prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// AS IS AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
// FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
// COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
// ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
